@isTest
private class WSCH_Provider_ECO_AppntmentWrpprDef_UT{

    static testMethod void WSCH_Provider_ECO_Appntment_WrapperDf_Test(){
                    
        SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.WSCH_Provider_ECO_Appointment_Settings appntmntSetting = new SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.WSCH_Provider_ECO_Appointment_Settings();
        SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.WSCH_Provider_ECO_Appointment_Request appntmntReqst = new SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.WSCH_Provider_ECO_Appointment_Request();
        SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.WSCH_Provider_ECO_Appointment_HeaderRecord appntmntHeaderRcrd = new SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.WSCH_Provider_ECO_Appointment_HeaderRecord();
        SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.WSCH_Provider_ECO_Appointment_Response appntmntRespnse = new SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.WSCH_Provider_ECO_Appointment_Response();
        SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.WSCH_Provider_ECO_Appointment_OfferAppointments appntmntOffrappnmts = new SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.WSCH_Provider_ECO_Appointment_OfferAppointments();
        SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.BookAppointmentRequest_WP appntmntBooking = new SVMXC.WSCH_Provider_ECO_AppointmentWrapperDef.BookAppointmentRequest_WP();
                            
    }

}